jobs:
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Run checkstyle verification
      run: ./gradlew checkstyleMain
name: Checkstyle
on:
  repository_dispatch:
    types: trigger-ga___checkstyle.yml
