jobs:
  jpackage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set Up Java18
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '18'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Release-win-zip
      run: ./gradlew app:releaseWinZip
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'windows')
      name: Release-win
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: 'app/build/jpackage/*.msi

          app/build/jpackage/*.zip

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'macos')
      name: Release-mac
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: 'app/build/jpackage/*.dmg

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
      name: Release-ubuntu
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: 'app/build/jpackage/*.rpm

          app/build/jpackage/*.deb

          '
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
